### ISSUE TITLE
i can`t see the info in the rows

### ISSUE THREAD

**Issue by FlaviaeGonzalez** [mbraak/simple-data-grid#14]
When i used the example i just see the rows empty, it appeared the all the rows but nothing inside, what do i do wrong?  I Put a json var but it doesn´t complete me the grid

**Comment by mbraak** [comment]
Which example did you use?

I used the following example, and it seems to work:

```html
<table id="demo-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Latin name</th>
    </tr>
  </thead>
</table>
<script>
    var data = [
      {
        "latin_name": "Persea americana",
        "name": "Avocado"
      },
      {
        "latin_name": "Capsicum annuum",
        "name": "Bell pepper"
      }
    ];

    $('#demo-table').simple_datagrid(
      {
        data: data
      }
    );
</script>
```

**Comment by FlaviaeGonzalez** [comment]
this is my code:
and the data isn´t display
<html>
<script src="mbraak\mbraak-simple-data-grid-087abb7\extra\jquery-1.11.1.min.js"></script>
<script src="mbraak\mbraak-simple-data-grid-087abb7\extra\bower_components\jquery\dist\jquery.min.js"></script>
<script src="mbraak\mbraak-simple-data-grid-087abb7\simple.datagrid.js"></script>
<link rel="stylesheet" href="mbraak\mbraak-simple-data-grid-087abb7\simple.datagrid.css">
<table id="demo-table">
  <thead>        
        <tr>
               <th>Nro</th>
               <th>MAQUINA</th>
        </tr>
  </thead>
</table>

<script>

var data = [
  {
    "Nro": "Persea americana",
    "MAQUINA": "Avocado"
  },
  {
    "Nro": "americana",
    "MAQUINA": "Avocado"
  },
  {
    "Nro": "Persea",
    "MAQUINA": "Avocado"
  },
   {
        "latin_name": "Capsicum annuum",
        "name": "Bell pepper"
      }
    ];

    $('#demo-table').simple_datagrid(
      {
        data: data
      }
    );

    $('#demo-table').simple_datagrid('loadData', data);
    
</script>
</html>

Date: Sun, 12 Apr 2015 23:50:22 -0700

**Comment by mbraak** [comment]
I think you can fix this by setting the ``data-key`` property on the ``th`` elements:

```html
      <th data-key="latin_name">Nro</th>
      <th data-key="name">MAQUINA</th>
```

**Comment by FlaviaeGonzalez** [comment]
thanks!!!! that wprks!!!!!!!!!!!!! the last thing that i need to ask (... i hope...) is if there is a way that it could work on ie9? 

Date: Mon, 13 Apr 2015 05:22:17 -0700

**Comment by mbraak** [comment]
Simple-data-grid should work in ie9. I tried the [docs](http://mbraak.github.io/simple-data-grid/) in ie9, and it seems to work.

**Comment by FlaviaeGonzalez** [comment]
I need to pass the json array from a php file, but it says: no rows. the name of the file is: grid.php and the json is in $dato, how do i do it?

my code:


<!DOCTYPE html>
<html>
<script src="mbraak\mbraak-simple-data-grid-087abb7\extra\jquery-1.11.1.min.js"></script>
<script src="mbraak\mbraak-simple-data-grid-087abb7\extra\bower_components\jquery\dist\jquery.min.js"></script>
<script src="mbraak\mbraak-simple-data-grid-087abb7\simple.datagrid.js"></script>
<link rel="stylesheet" href="mbraak\mbraak-simple-data-grid-087abb7\simple.datagrid.css">
<?php include "grid.php" ?>
<table id="demo-table" data-url="grid.php">
  <thead>        
        <tr> 
            <th data-key="IdMaquina">Nro</th>
            <th data-key="MaquinaModelo">MAQUINA</th>
        </tr>
  </thead>
</table>

<script>

var data= "<?php echo $dato; ?>";

    $('#demo-table').simple_datagrid(
      {
        data: data
      }
    );

$('#demo-table').simple_datagrid('loadData', data);


$('#demo-table').bind(
  'datagrid.load_data',
  function() {
    // Data is loaded
  }
);
</script>
</html>

**Comment by mbraak** [comment]
What does $dato look like. Is it a php array?

**Comment by FlaviaeGonzalez** [comment]
It´s a json array:

while ($row = mssql_fetch_assoc($result)) {
        $orders[] = array(    
        'IdMaquina' => $row['IdMaquina'],                
        'MaquinaModelo' => $row['MaquinaModelo'],                    
        'Articulo' => $row['Articulo'],                    
        );
    }
    
    $dato = json_encode($orders);

I put it that way so i can use it at the data of  the grid

Date: Mon, 13 Apr 2015 10:25:33 -0700

**Comment by mbraak** [comment]
I think you should remove the quotation marks around ``$dato`` in ``grid.pp``:

```js
var data = <?php echo $dato; ?>;
```

**Comment by FlaviaeGonzalez** [comment]
if i do that it cause error, because with quotation marks, js gets the sentences in php, so it doesn´t work, i just tried that since you said it but it didn´t work
Date: Mon, 13 Apr 2015 12:01:34 -0700

**Comment by mbraak** [comment]
Unfortunately I don't know much php.

The data in the resulting html should have this structure:

```js
var data = [
  {"latin_name": "Persea americana"},
  {"latin_name": "Capsicum annuum", "name": "Bell pepper"}
];
```
