### ISSUE TITLE
order_by doesn't re-order

### ISSUE THREAD

**Issue by embrilliant** [mbraak/simple-data-grid#15]
I added order_by like this:
```
$('#rate-table').simple_datagrid(
			  {
			    data: rateData,
			    order_by: "kurs"
			  }
			);
```
When I click the column it doesn't re-order.

**Comment by mbraak** [comment]
Simpledatagrid doesn't sort the data. It only displays the sortorder in the header.
I will mention this in the documentation, as I can see that this is confusing.
