### ISSUE TITLE
How to get pagination working...

### ISSUE THREAD

**Issue by kronus** [mbraak/simple-data-grid#16]
without using mockjax.

I have tried a few things such as:

ExampleData.pagedReponse() - but then, settings are not defined

$('#cj-table').simple_datagrid(
              {
                data: mOutput
              },
              {
                order_by: 'id'
              },
              {
                paginator: true
              }
            );

simple.datagrid.js:
paginator: null,

**Comment by mbraak** [comment]
Simple-data-grid can only paginate when the data is loaded from a url. In the examples I used mockjax to simulate this.

The first use case of simple-data-grid is to load data from a url. It is possible to load data using the ``data`` option, but that is only for testing purposes.

**Comment by kronus** [comment]
That makes complete sense. Thank you for your response
