### ISSUE TITLE
The data will not load if ...

### ISSUE THREAD

**Issue by GeirOttoOlsen** [mbraak/simple-data-grid#18]
This will NOT work:
[
{kundenr: "0001", kundenavn: "dummy"},
{kundenr: "09090909", kundenavn: "Testkunde"},
]
but this will...
[
{"kundenr": "0001", "kundenavn": "dummy"},
{"kundenr": "09090909", "kundenavn": "Testkunde"},
]
Isn't both of them valid json? It seems like I need to have " around both name and value... I used some hours finding this... is it a but,?

**Comment by mbraak** [comment]
Yes, you need `"` around the names. So the second example is valid json, and the first is not.
